### ISSUE TITLE
z-index support?

### ISSUE THREAD

**Issue by SevDaisy** [winder/bubblelayout#7]
I'm troubling with how can I render my boxes in different z-index? You know, just like the amazing video https://charm.sh/bubbletea.6f3a317d9ddacaed.mp4 in https://charm.sh/

anyway, source code enough for me in most cases. however I searched almost everywhere but find no code about the amazing MP4. closely to cry(.hahaha

Is it possiblely to support z-index with your lib NOW or FUTURE ?

**Comment by winder** [comment]
This library doesn't help with z-index. It is only designed to support tiled layouts, like most terminal applications.

I would love to see proper modal / floating window support in bubble tea and lipgloss, but I don't think they exist yet. The closest I'm aware of is the [place](https://github.com/charmbracelet/lipgloss#placing-text-in-whitespace) function, but I'm not sure how to provide a background buffer with it.

This old PR is the closest thing I'm aware of that would let you build a floating window / modal / overlay: https://github.com/charmbracelet/lipgloss/pull/102

Strange that they would use this as the demo video for bubble tea!
